/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpDataAnalysis: typeof import('~icons/ep/data-analysis')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpHome: typeof import('~icons/ep/home')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    IEpPlatform: typeof import('~icons/ep/platform')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpRefreshRight: typeof import('~icons/ep/refresh-right')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    PicCaptcha: typeof import('./src/components/pic-captcha.vue')['default']
    Process: typeof import('./src/components/process.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./src/components/icon/svg.vue')['default']
  }
}
